[package]
name = "clipcat"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
arboard = "3.6.0"
rand = "0.9.1"
